### ISSUE TITLE
fix(plugins/notable): possible issues

### ISSUE THREAD

**Issue by lowlighter** [lowlighter/metrics#1157]
### Discussed in https://github.com/lowlighter/metrics/discussions/1148

<div type='discussions-op-text'>

<sup>Originally posted by **jayvdb** July 22, 2022</sup>
For the notable plugin, I set `debug: true` and `plugin_notable_types: commit, issue, pull_request`, and obviously have `indepth` enabled, and now I am seeing quite a few of the following in the log

```
metrics/compute/jayvdb/plugins > notable > indepth > successfully processed ansible/ansible-lint
TypeError: contributions.filter is not a function
      at Object.default [as notable] (file:///metrics/source/plugins/notable/index.mjs:83:41)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async file:///metrics/source/plugins/core/index.mjs:67:30
      at async Promise.all (index 0)
      at async metrics (file:///metrics/source/app/metrics/index.mjs:64:22)
      at async retry.retries.retries (file:///metrics/source/app/action/index.mjs:398:34)
      at async retry (file:///metrics/source/app/action/index.mjs:57:22)
      at async file:///metrics/source/app/action/index.mjs:397:20
  metrics/compute/jayvdb/plugins > notable > indepth > failed to compute for pdm-project/pdm
  metrics/compute/jayvdb/plugins > notable > indepth > successfully processed TheLartians/ModernCppStarter
```
Run: https://github.com/jayvdb/jayvdb/runs/7468279468?check_suite_focus=true

I don't have any commits in that repo, but I did create an issue: https://github.com/pdm-project/pdm/issues/created_by/jayvdb

pdm now appears in my svg https://github.com/jayvdb/jayvdb/commit/01ec97176e18086d5cd4bd0fc70d35b065ea5698 without any of the numerical scores inside its circle.

So I am guessing that `plugin_notable_types` of `issue` & `pull_request` are incompatible with `indepth` at the moment, unless there was a commit also in the repo.

But the problem is a bit more nuanced than that, as I only have a rejected issue in https://github.com/TheLartians/ModernCppStarter/issues/131, and only an unmerged closed PR in https://github.com/ansible/ansible-lint/pull/2196 - both repos that were "successfully processed".</div>

**Comment by yuanweize** [comment]
Hi @lowlighter — I’m maintaining an independent community-maintained fork of `lowlighter/metrics` focused on compatibility fixes, security updates, and continued maintenance:
https://github.com/yuanweize/metrics-community

I’ve included this upstream issue in the fork’s migration/backlog tracking and plan to continue triaging it there.
This issue is tracked in the community fork here:
https://github.com/yuanweize/metrics-community/issues/23

The original report and discussion remain here and attribution stays with the original contributors. The fork is independent and is not an official successor to `lowlighter/metrics`.
If this still affects you, additional reproduction details or testing against the maintained fork would be very helpful.
