### ISSUE TITLE
fix(plugins/notable): fails when org uses SAML

### ISSUE THREAD

**Issue by lowlighter** [lowlighter/metrics#1371]
### Discussed in https://github.com/lowlighter/metrics/discussions/1362

<div type='discussions-op-text'>

<sup>Originally posted by **jayvdb** January 17, 2023</sup>
I would rather not give my metrics token SAML approval.  Can an org be skipped somehow?
```
  metrics/compute/jayvdb/plugins > notable > completed (error)
  {
    name: 'notable',
    result: {
      error: {
        message: 'Unexpected error',
        instance: GraphqlResponseError: Request failed due to following response errors:
         - Resource protected by organization SAML enforcement. You must grant your Personal Access token access to this organization.
            at /metrics/node_modules/@octokit/graphql/dist-node/index.js:70:13
            at runMicrotasks (<anonymous>)
            at processTicksAndRejections (node:internal/process/task_queues:96:5)
            at async Object.default [as notable] (file:///metrics/source/plugins/notable/index.mjs:20:62)
            at async file:///metrics/source/plugins/core/index.mjs:67:30
            at async Promise.all (index 0)
            at async metrics (file:///metrics/source/app/metrics/index.mjs:81:22)
            at async retry.retries.retries (file:///metrics/source/app/action/index.mjs:407:40)
            at async retry (file:///metrics/source/app/action/index.mjs:57:22)
            at async file:///metrics/source/app/action/index.mjs:406:28 {
          request: {
            query: 'query NotableContributions {\n' +
              '  user(login: "jayvdb") {\n' +
              '    repositoriesContributedTo(after: "Y3Vyc29yOnYyOpICzgktIp4=" first: 5, contributionTypes: [COMMIT, ISSUE, PULL_REQUEST], includeUserRepositories: false, orderBy: { field: STARGAZERS, direction: DESC'... 482 more characters
          },
```</div>

**Comment by scarf005** [comment]
Hi, i'm interested in opening a PR [(~~totally not because my workflow failed~~)](https://github.com/scarf005/scarf005/actions/runs/7418372124/job/20186206007#step:2:993). May I get a pointer on where to look at, and preferred solution?

also, should i open a PR on `v4-dev` or `main`?

**Comment by yuanweize** [comment]
Hi @lowlighter — I’m maintaining an independent community-maintained fork of `lowlighter/metrics` focused on compatibility fixes, security updates, and continued maintenance:
https://github.com/yuanweize/metrics-community

I’ve included this upstream issue in the fork’s migration/backlog tracking and plan to continue triaging it there.
This issue is tracked in the community fork here:
https://github.com/yuanweize/metrics-community/issues/16

The original report and discussion remain here and attribution stays with the original contributors. The fork is independent and is not an official successor to `lowlighter/metrics`.
If this still affects you, additional reproduction details or testing against the maintained fork would be very helpful.
