### ISSUE TITLE
Workflow fails with 'Error: Invalid request.  "sha" wasn't supplied.'

### ISSUE THREAD

**Issue by MatievisTheKat** [lowlighter/metrics#21]
**Bug description**
The workflow consistently fails with the error "Error: Invalid request. "sha" wasn't supplied." Additional logging above that shows that this is caused by the PUT request to update the SVG in the repo. (Request fails with a '422 Unprocessable Entity' status)

<details>
<summary>Complete Logs</summary>
<br>

```log
/usr/bin/docker run --name ce1bb4461fa94a6cb4848631ba9ce827_59973a --label 179394 --workdir /github/workspace --rm -e INPUT_TOKEN -e INPUT_COMMITTER_TOKEN -e INPUT_BASE -e INPUT_PLUGIN_ISOCALENDAR -e INPUT_PLUGIN_ISOCALENDAR_DURATION -e INPUT_PLUGIN_MUSIC -e INPUT_PLUGIN_MUSIC_PROVIDER -e INPUT_PLUGIN_MUSIC_TOKEN -e INPUT_PLUGIN_MUSIC_MODE -e INPUT_PLUGIN_MUSIC_LIMIT -e INPUT_PLUGIN_LANGUAGES -e INPUT_PLUGIN_FOLLOWUP -e INPUT_PLUGIN_TOPICS -e INPUT_PLUGIN_TOPICS_SORT -e INPUT_PLUGIN_TOPICS_LIMIT -e INPUT_PLUGIN_LINES -e INPUT_PLUGIN_HABITS -e INPUT_PLUGIN_HABITS_FROM -e INPUT_PLUGIN_PAGESPEED -e INPUT_PLUGIN_PAGESPEED_TOKEN -e INPUT_PLUGIN_PAGESPEED_DETAILED -e INPUT_USER -e INPUT_FILENAME -e INPUT_OPTIMIZE -e INPUT_REPOSITORIES -e INPUT_TEMPLATE -e INPUT_PLUGIN_TRAFFIC -e INPUT_PLUGIN_MUSIC_PLAYLIST -e INPUT_PLUGIN_POSTS -e INPUT_PLUGIN_POSTS_SOURCE -e INPUT_PLUGIN_POSTS_LIMIT -e INPUT_PLUGIN_GISTS -e INPUT_PLUGIN_PROJECTS -e INPUT_PLUGIN_PROJECTS_LIMIT -e INPUT_DEBUG -e INPUT_VERIFY -e INPUT_DRYRUN -e INPUT_PLUGINS_ERRORS_FATAL -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/MatievisTheKat/MatievisTheKat":"/github/workspace" 179394:ce1bb4461fa94a6cb4848631ba9ce827
GitHub metrics as SVG image
========================================================
Version             | 2.7.0
Configuration       | loaded
Template to use     | classic
Github token        | provided
Github GraphQL API  | ok
Github REST API     | ok
SVG output file     | github-metrics.svg
SVG optimization    | true
GitHub user         | MatievisTheKat
Debug mode          | false
Base parts          | header, activity, community, repositories, metadata
Plugins enabled     | lines, pagespeed, habits, languages, followup, music, isocalendar, topics
Pagespeed token     | provided
Pagespeed detailed  | true
Music provider      | spotify
Music plugin mode   | recent
Music playlist      | null
Music tracks limit  | 5
Music token         | provided
Isocalendar duration| full-year
Topics sort mode    | stars
Topics limit        | 15
Repositories to use | 100
Plugin errors       | ignore
BQCXNX9Ikh0YU2eMCac2nb_POS0ysHz45QlGm3E6kXth6sk471qXlMM_1vvHZWX9MI7tSKneG9PMO-OzpqtJhHZ9si-0CkVCLzYSR-kWCyH55lLuOSGKhhT_wUGZLBwILGc6sIVBlyi31B463GQyaJf2
Render              | complete
Verify SVG          | false
Repository          | MatievisTheKat/MatievisTheKat
Committer token     | provided
Committer REST API  | ok
Committer           | (unknown)
Previous render sha | none
s [HttpError]: Invalid request.

"sha" wasn't supplied.
    at /index.js:66:81955
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async /index.js:66:8738 {
  status: 422,
  headers: {
    'access-control-allow-origin': '*',
    'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset',
    connection: 'close',
    'content-length': '156',
    'content-security-policy': "default-src 'none'",
    'content-type': 'application/json; charset=utf-8',
    date: 'Tue, 15 Dec 2020 14:22:27 GMT',
    'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
    server: 'GitHub.com',
    status: '422 Unprocessable Entity',
    'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
    vary: 'Accept-Encoding, Accept, X-Requested-With',
    'x-content-type-options': 'nosniff',
    'x-frame-options': 'deny',
    'x-github-media-type': 'github.v3; format=json',
    'x-github-request-id': '07C4:7DA0:D6C507:2238722:5FD8C6A3',
    'x-ratelimit-limit': '1000',
    'x-ratelimit-remaining': '967',
    'x-ratelimit-reset': '1608043777',
    'x-ratelimit-used': '33',
    'x-xss-protection': '1; mode=block'
  },
  request: {
    method: 'PUT',
    url: 'https://api.github.com/repos/MatievisTheKat/MatievisTheKat/contents/github-metrics.svg',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit-core.js/3.2.1 Node.js/15.4.0 (linux; x64)',
      authorization: 'token [REDACTED]',
      'content-type': 'application/json; charset=utf-8'
    },
    body: '{"message":"Update github-metrics.svg - [Skip GitHub Action]","content":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI0ODAiIGhlaWdodD0iMTU3MCI+PGRlZnM+PHN0eWxlLz48L2RlZnM+PHN0eWxlPi8qIFNWRyBnbG9iYWwgY29udGV4dCAqLyBzdmcgeyBmb250LWZhbWlseTogLWFwcGxlLXN5c3RlbSwgQmxpbmtNYWNTeXN0ZW1Gb250LCBTZWdvZSBVSSwgSGVsdmV0aWNhLCBBcmlhbCwgc2Fucy1zZXJpZiwgQXBwbGUgQ29sb3IgRW1vamksIFNlZ29lIFVJIEVtb2ppOyBmb250LXNpemU6IDE0cHg7IGNvbG9yOiAjNzc3Nzc3OyB9IC8qIEhlYWRlcnMgKi8gaDEsIGgyLCBoMyB7IG1hcmdpbjogOHB4IDAgMnB4OyBwYWRkaW5nOiAwOyBjb2xvcjogIzAzNjZkNjsgZm9udC13ZWlnaHQ6IG5vcm1hbDsgfSBoMSBzdmcsIGgyIHN2ZywgaDMgc3ZnIHsgZmlsbDogY3VycmVudENvbG9yOyB9IGgxIHsgZm9udC1zaXplOiAyMHB4OyBmb250LXdlaWdodDogYm9sZDsgfSBoMiB7IGZvbnQtc2l6ZTogMTZweDsgfSBoMyB7IGZvbnQtc2l6ZTogMTRweDsgfSAvKiBGaWVsZHMgKi8gc2VjdGlvbiAmZ3Q7IC5maWVsZCB7IG1hcmdpbi1sZWZ0OiA1cHg7IG1hcmdpbi1yaWdodDogNXB4OyB9IC5maWVsZCB7IGRpc3BsYXk6IGZsZXg7IGFsaWduLWl0ZW1zOiBjZW50ZXI7IG1hcmdpbi1ib3R0b206IDJweDsgd2hpdGUtc3BhY2U6IG5vd3JhcDsgfSAuZmllbGQgc3ZnIHsgbWFyZ2luOiAwIDhweDsgZmlsbDogIzk1OWRhNTsgZmxleC1zaHJpbms6IDA7IH0gLmZpZWxkLmVycm9yIHsgY29sb3I6ICNjYjI0MzE7IH0gLmZpZWxkLmVycm9yIHN2ZyB7IGZpbGw6ICNjYjI0MzE7IH0gLyogRGlzcGxheXMgKi8gLnJvdyB7IGRpc3BsYXk6IGZsZXg7IH0gLnJvdyBzZWN0aW9uIHsgZmxleDogMSAxIDA7IH0gLmNvbHVtbiB7IGRpc3BsYXk6IGZsZXg7IGZsZXgtZGlyZWN0aW9uOiBjb2x1bW47IGFsaWduLWl0ZW1zOiBjZW50ZXI7IH0gLmNlbnRlciB7IGp1c3RpZnktY29udGVudDogY2VudGVyOyB9IC5ob3Jpem9udGFsIHsganVzdGlmeS1jb250ZW50OiBzcGFjZS1hcm91bmQ7IH0gLmhvcml6b250YWwtd3JhcCB7IGZsZXgtd3JhcDogd3JhcDsgfSAuaG9yaXpvbnRhbCAuZmllbGQgeyBmbGV4OiAxIDEgMDsgfSAubm8td3JhcCB7IHdoaXRlLXNwYWNlOiBub3dyYXA7IH0gLmZpbGwtd2lkdGggeyB3aWR0aDogMTAwJTsgfSAvKiBVc2VyIGF2YXRhciAqLyAuYXZhdGFyIHsgYmFja2dyb3VuZC1jb2xvcjogIzAwMDAwMDsgYm9yZGVyLXJhZGl1czogNTAlOyBtYXJnaW46IDAgNnB4OyB9IC8qIENvbW1pdCBjYWxlbmRhciAqLyAuY2FsZW5kYXIuZmllbGQgeyBtYXJnaW46IDRweCAwOyBtYXJnaW4tbGVmdDogN3B4OyB9IC5jYWxlbmRhciAuZGF5IHsgb3V0bGluZTogMXB4IHNvbGlkIHJnYmEoMjcsMzEsMzUsLjA0KTsgb3V0bGluZS1vZmZzZXQ6IC0xcHg7IH0gLyogUHJvZ3Jlc3MgYmFycyAqLyBzdmcuYmFyIHsgbWFyZ2luOiA0cHggMDsgfSAvKiBMYW5ndWFnZSAqLyAuZmllbGQubGFuZ3VhZ2UgeyBtYXJnaW46IDAgOHB4OyBmbGV4LWdyb3c6IDA7IH0gLmZpZWxkLmxhbmd1YWdlIHNtYWxsIHsgbWFyZ2luLWxlZnQ6IDRweDsgb3BhY2l0eTogLjc7IH0gLyogTGFiZWxzICovIC5sYWJlbCB7IGJhY2tncm91bmQtY29sb3I6ICNGMUY4RkY7IGNvbG9yOiAjMDM2NkQ2OyBwYWRkaW5nOiAwIDEwcHg7IGZvbnQtd2VpZ2h0OiA1MDA7IGxpbmUtaGVpZ2h0OiAyMnB4OyBtYXJnaW46IDJweCA1cHg7IHdoaXRlLXNwYWNlOiBub3dyYXA7IGJvcmRlci1yYWRpdXM6IDMycHg7IGZvbnQtc2l6ZTogMTJweDsgfSAubGFiZWw6aG92ZXIgeyBiYWNrZ3JvdW5kLWNvbG9yOiAjRERFRUZGOyBjdXJzb3I6IHBvaW50ZXI7IH0gLyogSGFiaXRzICovIC5oYWJpdHMgeyBtYXJnaW46IDA7IGxpc3Qtc3R5bGUtdHlwZTogbm9uZTsgcGFkZGluZy1sZWZ0OiAzN3B4OyB9IC8qIEZvb3RlciAqLyBmb290ZXIgeyBtYXJnaW4tdG9wOiA4cHg7IGZvbnQtc2l6ZTogMTBweDsgZm9udC1zdHlsZTogaXRhbGljOyBvcGFjaXR5OiAwLjU7IHRleHQtYWxpZ246IHJpZ2h0OyBkaXNwbGF5OiBmbGV4OyBmbGV4LWRpcmVjdGlvbjogY29sdW1uOyBqdXN0aWZ5LWNvbnRlbnQ6IGZsZXgtZW5kOyB9IC8qIFNwZWVkIHRlc3QgY2F0ZWdvcmllcyAqLyAuY2F0ZWdvcmllcyB7IGRpc3BsYXk6IGZsZXg7IGFsaWduLWl0ZW1zOiBjZW50ZXI7IGp1c3RpZnktY29udGVudDogc3BhY2UtYXJvdW5kOyBtYXJnaW4tdG9wOiA0cHg7IH0gLmNhdGVnb3JpZSB7IGRpc3BsYXk6IGZsZXg7IGZsZXgtZGlyZWN0aW9uOiBjb2x1bW47IGFsaWduLWl0ZW1zOiBjZW50ZXI7IGZsZXg6IDEgMSAwOyB9IC8qIEdhdWdlcyAqLyAuZ2F1Z2UgeyBzdHJva2UtbGluZWNhcDogcm91bmQ7IGZpbGw6IG5vbmU7IH0gLmdhdWdlLmhpZ2ggeyBjb2xvcjogIzE4YjY2MzsgfSAuZ2F1Z2UuYXZlcmFnZSB7IGNvbG9yOiAjZmI4YzAwOyB9IC5nYXVnZS5sb3cgeyBjb2xvcjogI2U1MzkzNTsgfSAuZ2F1Z2UtYmFzZSwgLmdhdWdlLWFyYyB7IHN0cm9rZTogY3VycmVudENvbG9yOyBzdHJva2Utd2lkdGg6IDEwOyB9IC5nYXVnZS1iYXNlIHsgc3Ryb2tlLW9wYWNpdHk6IC4yOyB9IC5nYXVnZS1hcmMgeyBmaWxsOiBub25lOyBzdHJva2UtZGFzaG9mZnNldDogMDsgYW5pbWF0aW9uLWRlbGF5OiAyNTBtczsgYW5pbWF0aW9uOiBhbmltYXRpb24tZ2F1Z2UgMXMgZWFzZSBmb3J3YXJkcyB9IC5nYXVnZSB0ZXh0IHsgZmlsbDogY3VycmVudENvbG9yOyBmb250LXNpemU6IDQwcHg7IGZvbnQtZmFtaWx5OiBtb25vc3BhY2U7IHRleHQtYW5jaG9yOiBtaWRkbGU7IGZvbnQtd2VpZ2h0OiA2MDA7IH0gLmdhdWdlIC50aXRsZSB7IGZvbnQtc2l6ZTogMThweDsgY29sb3I6ICM3Nzc3Nzc7IH0gQGtleWZyYW1lcyBhbmltYXRpb24tZ2F1Z2UgeyBmcm9tIHsgc3Ryb2tlLWRhc2hhcnJheTogMCAzMjk7IH0gfSAuYXVkaXRzIHsgbWFyZ2luLXRvcDogOHB4OyB9IC5hdWRpdC50ZXh0IHsgbWluLXdpZHRoOiA0MnB4OyB9IC5hdWRpdCBzdmcgeyBtYXJnaW46IDA7IH0gLmF1ZGl0LmhpZ2ggeyBmaWxsOiAjMThiNjYzOyB9IC5hdWRpdC5hdmVyYWdlIHsgZmlsbDogI2ZiOGMwMDsgfSAuYXVkaXQubG93IHsgZmlsbDogI2U1MzkzNTsgfSAvKiBNdXNpYyBwbHVnaW4gKi8gLnRyYWNrbGlzdCB7IGRpc3BsYXk6IGZsZXg7IGZsZXgtZGlyZWN0aW9uOiBjb2x1bW47IGFsaWduLWl0ZW1zOiBmbGV4LXN0YXJ0OyBtYXJnaW4tbGVmdDogMjhweDsgbWFyZ2luLXRvcDogNHB4OyB3aWR0aDogMTAwJTsgfSAudHJhY2sgeyBkaXNwbGF5OiBmbGV4OyBhbGlnbi1pdGVtczogY2VudGVyOyBqdXN0aWZ5LWNvbnRlbnQ6IGNlbnRlcjsgbWFyZ2luLWJvdHRvbTogNHB4OyB9IC50cmFjayBpbWcgeyBtYXJnaW46IDAgMTBweDsgYm9yZGVyLXJhZGl1czogN3B4OyB9IC50cmFjayAubmFtZSB7IGZvbnQtc2l6ZTogMTRweDsgbGluZS1oZWlnaHQ6IDE0cHg7IH0gLnRyYWNrIC5hcnRpc3QgeyBmb250LXNpemU6IDEycHg7IG9wYWNpdHk6IC43OyB9IC8qIFBvc3RzIHBsdWdpbiAqLyAucG9zdCB7IGFsaWduLWl0ZW1zOiBmbGV4LXN0YXJ0OyB9IC5wb3N0IC5pbmZvcyB7IGRpc3BsYXk6IGZsZXg7IG1hcmdpbi1ib3R0b206IDRweDsgfSAucG9zdCAuaW5mb3MgLnRpdGxlIHsgZm9udC1zaXplOiAxNHB4OyB3aWR0aDogNDAwcHg7IHdoaXRlLXNwYWNlOiBub3JtYWw7IG92ZXJmbG93OiBoaWRkZW47IHRleHQtb3ZlcmZsb3c6IGVsbGlwc2lzOyBtYXgtaGVpZ2h0OiA0MHB4OzsgfSAucG9zdCAuaW5mb3MgLmRhdGUgeyBmbGV4LXNocmluazogMDsgZm9udC1zaXplOiAxMnB4OyBvcGFjaXR5OiAuNzsgd2lkdGg6IDQwcHg7IHBhZGRpbmctdG9wOiAxcHg7IH0gLyogVG9waWNzICovIC50b3BpY3MgeyBkaXNwbGF5OiBmbGV4OyBmbGV4LXdyYXA6IHdyYXA7IH0gLyogRmFkZSBhbmltYXRpb24gKi8gLmFmIHsgb3BhY2l0eTogMDsgYW5pbWF0aW9uOiBhbmltYXRpb24tZmFkZSAxcyBlYXNlIGZvcndhcmRzOyB9IEBrZXlmcmFtZXMgYW5pbWF0aW9uLWZhZGUgeyBmcm9tIHsgb3BhY2l0eTogMDsgfSB0byB7IG9wYWNpdHk6IDE7IH0gfSAvKiBDYWxlbmRhciAqLyA6cm9vdCB7IC0tY29sb3ItY2FsZW5kYXItZ3JhcGgtZGF5LWJnOiAjZWJlZGYwOyAtLWNvbG9yLWNhbGVuZGFyLWdyYXBoLWRheS1ib3JkZXI6IHJnYmEoMjcsMzEsMzUsMC4wNik7IC0tY29sb3ItY2FsZW5kYXItZ3JhcGgtZGF5LUwxLWJnOiAjOWJlOWE4OyAtLWNvbG9yLWNhbGVuZGFyLWdyYXBoLWRheS1MMi1iZzogIzQwYzQ2MzsgLS1jb2xvci1jYWxlbmRhci1ncmFwaC1kYXktTDMtYmc6ICMzMGExNGU7IC0tY29sb3ItY2FsZW5kYXItZ3JhcGgtZGF5LUw0LWJnOiAjMjE2ZTM5OyAtLWNvbG9yLWNhbGVuZGFyLWhhbGxvd2Vlbi1ncmFwaC1kYXktTDEtYmc6ICNmZmVlNGE7IC0tY29sb3ItY2FsZW5kYXItaGFsbG93ZWVuLWdyYXBoLWRheS1MMi1iZzogI2ZmYzUwMTsgLS1jb2xvci1jYWxlbmRhci1oYWxsb3dlZW4tZ3JhcGgtZGF5LUwzLWJnOiAjZmU5NjAwOyAtLWNvbG9yLWNhbGVuZGFyLWhhbGxvd2Vlbi1ncmFwaC1kYXktTDQtYmc6ICMwMzAwMWM7IC0tY29sb3ItY2FsZW5kYXItZ3JhcGgtZGF5LUw0LWJvcmRlcjogcmdiYSgyNywzMSwzNSwwLjA2KTsgLS1jb2xvci1jYWxlbmRhci1ncmFwaC1kYXktTDMtYm9yZGVyOiByZ2JhKDI3LDMxLDM1LDAuMDYpOyAtLWNvbG9yLWNhbGVuZGFyLWdyYXBoLWRheS1MMi1ib3JkZXI6IHJnYmEoMjcsMzEsMzUsMC4wNik7IC0tY29sb3ItY2FsZW5kYXItZ3JhcGgtZGF5LUwxLWJvcmRlcjogcmdiYSgyNywzMSwzNSwwLjA2KTsgfTwvc3R5bGU+PGZvcmVpZ25PYmplY3QgeD0iMCIgeT0iMCIgd2lkdGg9IjEwMCUiIGhlaWdodD0iMTAwJSI+PGRpdiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94aHRtbCIgeG1sbnM6eGxpbms9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGxpbmsiPjxzZWN0aW9uPjxoMSBjbGFzcz0iZmllbGQiPjxpbWcgY2xhc3M9ImF2YXRhciIgc3JjPSJkYXRhOmltYWdlL3BuZztiYXNlNjQsLzlqLzJ3Q0VBQWdHQmdjR0JRZ0hCd2NKQ1FnS0RCUU5EQXNMREJrU0V3OFVIUm9mSGgwYUhCd2dKQzRuSUNJc0l4d2NLRGNwTERBeE5EUTBIeWM1UFRneVBDNHpORElCQ1FrSkRBc01HQTBOR0RJaEhDRXlNakl5TWpJeU1qSXlNakl5TWpJeU1qSXlNakl5TWpJeU1qSXlNakl5TWpJeU1qSXlNakl5TWpJeU1qSXlNakl5TXYvQUFCRUlBY3dCekFNQklnQUNFUUVERVFIL3hBR2lBQUFCQlFFQkFRRUJBUUFBQUFBQUFBQUFBUUlEQkFVR0J3Z0pDZ3NRQUFJQkF3TUNCQU1GQlFRRUFBQUJmUUVDQXdBRUVRVVNJVEZCQmhOUllRY2ljUlF5Z1pHaENDTkNzY0VWVXRId0pETmljb0lKQ2hZWEdCa2FKU1luS0NrcU5EVTJOemc1T2tORVJVWkhTRWxLVTFSVlZsZFlXVnBqWkdWbVoyaHBhbk4wZFhaM2VIbDZnNFNGaG9lSWlZcVNrNVNWbHBlWW1acWlvNlNscHFlb3FhcXlzN1MxdHJlNHVickN3OFRGeHNmSXljclMwOVRWMXRmWTJkcmg0dVBrNWVibjZPbnE4Zkx6OVBYMjkvajUrZ0VBQXdFQkFRRUJBUUVCQVFBQUFBQUFBQUVDQXdRRkJnY0lDUW9MRVFBQ0FRSUVCQU1FQndVRUJBQUJBbmNBQVFJREVRUUZJVEVHRWtGUkIyRnhFeUl5Z1FnVVFwR2hzY0VKSXpOUzhCVmljdEVLRmlRMDRTWHhGeGdaR2lZbktDa3FOVFkzT0RrNlEwUkZSa2RJU1VwVFZGVldWMWhaV21Oa1pXWm5hR2xxYzNSMWRuZDRlWHFDZzRTRmhvZUlpWXFTazVTVmxwZVltWnFpbzZTbHBxZW9xYXF5czdTMXRyZTR1YnJDdzhURnhzZkl5Y3JTMDlUVjF0ZlkyZHJpNCtUbDV1Zm82ZXJ5OC9UMTl2ZjQrZnIvMmdBTUF3RUFBaEVERVFBL0FPTGV5UllJWTdXZWN5eTRMSnUzQmV2VDBxRFU3eSswQzZqdEk1M3VQTUJKRW5PUHBYUzZpOXRGY0NXMkpsTWcrZmN2Q0RuQUdPMVljdHFkWTFaYmdYQ3BERVFESTZrWVh2OEExcno0MmU1NlVuZU40czB0Sm5lL0JDWGMxbklrWVlSREd4dHd5U1FmOGlvZFJ1RlMyRmpjeHVOdUdhVU1yNVBmUHB5VHhUZFlzSWhIOXIwZWFWMUhCK1hJL1NxdGpvMm9hakZMNW9WcmFGaXJOT3Z6bGlPRlU5U2ZhcWpaTXo1bTFabHNTcGYyWWlSenRFV1kwOHJIQXdlY242MWFndDNiVEdsbGxrbE14QVZXYnFGOUIzeFMvd0JuK1JwNkNlWUxPb3lpcWR2QzQ0SS9IQnE1WWFkYjNadEVVT3NzZVZqNnFwSHVjVTIwWEJKTTBiL1NyVnRNdEFzdXd0RUhSdDJOdnIxcUxRSllyRzAreHdMR3Ztdm56R0c1bUE3ZXVLcXphMWV5Mjg5dExCRmdPRWlYY0NUanNQcldjMDgybFhDektyeDc4SC9ybm4xN1ZDZDJaVkhENFdkdEd0amZSWE1FN3I5bmlsS2xpZHZmR2VmVG1xZXJlQVpmSWoxVFE3cDJsVUVzcnNEbjFLbjg2NFN4MCtiVjlKMWNtUnBSRUJJeGtreGtaSEpQWC84QVZYWCtIUEgxaG9maFpMSzlXNDgyRUh5RkM1M3FPb3owNFBGWHNSQ050RG1iZXpNOXdSZW9TMXMrV1UvTHZicHo5VDJyb0xpT0NlMGthOFZFVUQ5Mk00eHhqajg2TE9hR1pMNjh1b0Z0NFFOeWJtM0VzeEpKUHR4aXNQVUlkVXY0VGVXMERTV3lrTU1MbG94MkJIcDdpc21uSm5STjhzYkk2YlI0TFVlZE5OY3lKSEhFSGZ6SEJCNStWQUIwSFhqclVaMG1YVVh1cmExWlk3ZThBWmtNaE93anB0K282ajJxZTlTS0x3K3NnamtpTWtZbE9WNnR0QUpCcWhZYXhMQkl6eVdmekVaU1FaQUh1UlZ4aW10REZMa3N6bFVFMWw0bW1obW1rKzAyMHJCNUZsSytaZ2NEK1dSNlZ1MjNpSzlra1lTc2pXMGtYNzFYazJnRUFENWMrdy9HckhpSzYwblVOUHVMenlndDZjTSt3Z2I4Y2ZnY1lybDBlSzIyUlh6TDVFaTdnQ29QeS9Xb2NiN21rWUozYlpwUXhRWE13TXNya1JCbzBNTEFaejcrdUNhazFPMDA0d21OTHFSU1dCL2VEZmtET0JXVGNhY3pTdkhvNW4reStXQ2ozQi9Nai84QVdhUzVoZlR0UUhsdTdQYngrV001eDBBWTQ3NUp6VFVDbnkvRGE1MW1sVzE1cW1rUlJYQmViN0t5MjZDTndHa3lPTjJlbkdPZnJXL3BQZ1hRTFNlWmJpeURYS25hcEZ3emdqaGdlZ3hqL0htdUF1OUUxQjlNaGxzbmtkcmxVYzdKZ3NoQzl4MDV5ZW50WFlhSnFlcXl3UjJJall6MjlxTXRMOHJPK1RuUFVqdHpTbGRhM0xWcjh0alI4VmFIcDBPbU0rbnd4eDNTakNONWpEYWNmV3ZOYis0aVM5SzM3dUVPMGgwR1RnNHovV3R5NnVOVXU0eGY2aEE2a3liWTRjbjZjblBYTlkycnlRVzkrSko3Ykx4QUZnajdnRzlDRHhRcnJjeWxmbTJPcDBuUm9MUzRsZ3RKU1lWaGFUZElSOTQ0d3VjWjlhMXRCdXJrM2theVNNNmdoY2RFT0IzejE2Vmc2UnJjK29XVGVWcDh5ekllUjVlVTY4RUhINTFUdnZFbXBYRU9ObjltMzFvd01zSkFPVnprWTlxVUkzbGRrTk42STlDbXNKcDBOMXA5MFlycDNZcVNnMmhTUmxPbkl5UHI3MXhyYWJkeU5meDM1dUI1RGdvUys0U1o1UFVaQS9IRkxhZVBwYm0wbU5rTjkwa2dFa0VoNkwwSitnOWZldERUUEVkdnJYbjJFMG9lODh2YktBbXdmaDlLMGxaTzZGQ2Jpck04NXVkSmtqaFp4YVJ3ZVd4ZmlZdWVjWUl6NjRyZXNaWnA5UTBlOWRjcmp5SndCbk9Ca0g4dUt1WGVnMitqSTF3Wm5hSm0yK1c3Nzl5blBmSCtjVkJwK3F'... 2315867 more characters,
    request: { agent: [Agent], hook: [Function: bound bound t] }
  },
  documentation_url: 'https://docs.github.com/rest/reference/repos#create-or-update-file-contents'
}
Error: Invalid request.

"sha" wasn't supplied.
```
</details>

<details>
<summary>My metrics.yml</summary>
<br>

```yml
name: GitHub metrics
on:
  # Schedule updates
  schedule: [{cron: "0 * * * *"}]
  push: {branches: "master"}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          # GITHUB_TOKEN is a special auto-generated token restricted to current repository, which is used to push files in it
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: header, activity, community, repositories, metadata
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_token: "${{ secrets.SPOTIFY_CLIENT_ID }}, ${{ secrets.SPOTIFY_CLIENT_SECRET }}, ${{ secrets.SPOTIFY_REFRESH_TOKEN }}"
          plugin_music_mode: recent
          plugin_music_limit: 5
          plugin_languages: yes
          plugin_followup: yes
          plugin_topics: yes
          plugin_topics_sort: stars
          plugin_topics_limit: 15
          plugin_lines: yes
          plugin_habits: yes
          plugin_habits_from: 100
          plugin_pagespeed: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugin_pagespeed_detailed: yes
```
</details>

**Expected behavior**
The workflow runs and updates the SVG

**To Reproduce**
Create a repo and use the configuration above

**Comment by Napolitain** [comment]
Happens to me also, additional question is why 2 workers? If both jobs are done at the same time always, I'd keep just one, making for faster workflows and less time usage of GitHub Actions API.

**Comment by MatievisTheKat** [comment]
Update: disabling plugins doesn't change the output

**Comment by lowlighter** [comment]
Hi ! 

@MatievisTheKat 
I'll investigate on this error case and try to fix it quickly 👍 

@Napolitain 
Seems you already changed it, but yeah my personal workflow has actually one worker for my own profile, and the other one generates the examples for this repository's readme. Since the later can be quite long, I often disable it when I just want to test stuff quickly 🙂

**Comment by lowlighter** [comment]
@MatievisTheKat 
Seems fixed now ! 

The endpoint used to retrieve the sha was not supporting files larger than 1Mb (hence why it worked at first but failed later). Now it should be fine. 

Thanks for the feedback !

**Comment by MatievisTheKat** [comment]
Wow awesome! Thanks for the speedy response!
