### ISSUE TITLE
Recent activity exception

### ISSUE THREAD

**Issue by Nixinova** [lowlighter/metrics#305]
The workflow errors out when creating my recent activity section

```
  {
    name: 'activity',
    result: {
      error: {
        message: 'An error occured',
        instance: TypeError: Cannot read property 'message' of undefined
            at file:///metrics/source/plugins/activity/index.mjs:124:47
            at Array.map (<anonymous>)
            at Object.default [as activity] (file:///metrics/source/plugins/activity/index.mjs:45:10)
            at processTicksAndRejections (node:internal/process/task_queues:94:5)
            at async file:///metrics/source/plugins/core/index.mjs:43:30
            at async Promise.all (index 0)
            at async metrics (file:///metrics/source/app/metrics/index.mjs:60:22)
            at async file:///metrics/source/app/action/index.mjs:290:24
      }
    }
  }
```

**Comment by Nixinova** [comment]
Ah, did https://github.com/lowlighter/metrics/commit/421a77096706af09760511dd65e265e418f5e65f fix it?

**Comment by lowlighter** [comment]
Yes it should have fixed it, but I have no idea how push events with 0 commits exists 😅

**Comment by Nixinova** [comment]
It was from `git push -f` after a `git reset`
