### ISSUE TITLE
File url can be undefined

### ISSUE THREAD

**Issue by Nixinova** [lowlighter/metrics#415]
Metrics run failed with the following error:

```yaml
metrics/compute/Nixinova > 2 errors !
[
  {
    name: 'languages',
    result: {
      error: {
        message: 'An error occured',
        instance: TypeError: Cannot read property 'match' of null
            at file:///metrics/source/plugins/languages/analyzers.mjs:87:175
            at Array.map (<anonymous>)
            at file:///metrics/source/plugins/languages/analyzers.mjs:87:27
            at Array.flatMap (<anonymous>)
            at recent (file:///metrics/source/plugins/languages/analyzers.mjs:87:4)
            at runMicrotasks (<anonymous>)
            at processTicksAndRejections (node:internal/process/task_queues:96:5)
            at async Object.default [as languages] (file:///metrics/source/plugins/languages/index.mjs:59:35)
            at async file:///metrics/source/plugins/core/index.mjs:50:30
            at async Promise.all (index 4)
      }
    }
  }
]
#...
```

**Comment by Nixinova** [comment]
https://github.com/lowlighter/metrics/blob/f22a6d613c480e755ba9e330478a3a003b020858/source/plugins/languages/analyzers.mjs#L87

`repo:file.raw_url.match` - apparently raw_url is nullable

**Comment by lowlighter** [comment]
#416 should stop the plugin crash
Reopening in case we can find the real root cause of having `file.repo_url` undefined
