### ISSUE TITLE
Tests exceed timeout

### ISSUE THREAD

**Issue by matievisthekat** [lowlighter/metrics#677]
This issue is in regard to #675 (specifically the test workflow [here](https://github.com/lowlighter/metrics/runs/4321208293?check_suite_focus=true).

The test suite fails with the message:
```
● GitHub Action › Template : classic › Poopmap plugin (default)

thrown: "Exceeded timeout of 60000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      118 |         test.skip(name, () => null)
      119 |       else
    > 120 |         test(name, async () => expect(await action.run({ template, base: "", query: JSON.stringify(query), plugins_errors_fatal: true, dryrun: true, use_mocked_data: true, verify: true, ...input })).toBe(true), timeout)
          |         ^
      121 |     }
      122 |   }))
      123 |

      at tests/metrics.test.js:120:9
          at Array.forEach (<anonymous>)
      at tests/metrics.test.js:115:5
```

This issue is reproducible on at 0896c9257a8c7bf894cbeaa6d765b181823fc46d.

The related EJS partial is available [here](https://github.com/matievisthekat/metrics/blob/plugin/poopmap/source/templates/classic/partials/poopmap.ejs)

It is unclear (to me) as to what is causing this timeout

**Comment by lowlighter** [comment]
Hi!

You need to expand the attempts to get logs.
Here's the error:
```
            error: {
              message: 'An error occured',
              instance: Error: Request failed with status code 404
        at createError (node_modules/axios/lib/core/createError.js:16:15)
        at settle (node_modules/axios/lib/core/settle.js:17:12)
        at IncomingMessage.handleStreamEnd (node_modules/axios/lib/adapters/http.js:293:11)
        at processTicksAndRejections (node:internal/process/task_queues:83:21) {
                config: {
                  transitional: {
                    silentJSONParsing: true,
                    forcedJSONParsing: true,
                    clarifyTimeoutError: false
                  },
                  adapter: [Function: httpAdapter],
                  transformRequest: [ [Function: transformRequest] ],
                  transformResponse: [ [Function: transformResponse] ],
                  timeout: 0,
                  xsrfCookieName: 'XSRF-TOKEN',
                  xsrfHeaderName: 'X-XSRF-TOKEN',
                  maxContentLength: -1,
                  maxBodyLength: -1,
                  validateStatus: [Function: validateStatus],
                  headers: {
                    Accept: 'application/json, text/plain, */*',
                    'User-Agent': 'axios/0.24.0'
                  },
                  method: 'get',
                  url: 'https://api.poopmap.net/api/v1/public_links/',
                  data: undefined
                },
```

See https://github.com/lowlighter/metrics/pull/675#discussion_r757162335 (basically `token` is empty so you end up on a 404)

**Comment by matievisthekat** [comment]
Ah, that makes sense
